# Dockerfile
FROM node:22-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY public/env.js /usr/share/nginx/html/env.jsz
EXPOSE 80
CMD sh -c "sed -i \"s/__POD_NAME__/$POD_NAME/g\" /usr/share/nginx/html/env.js && nginx -g 'daemon off;'"
