apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameapp
  template:
    metadata:
      labels:
        app: gameapp
    spec:
      containers:
      - name: gameapp
        image: tejubagalad/gameapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gameapp-service
spec:
  selector:
    app: gameapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

