apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamehub
spec:
  replicas: 1           # 🔹 CHANGE 1: multiple replicas
  selector:
    matchLabels:
      app: gamehub
  template:
    metadata:
      labels:
        app: gamehub
    spec:
      containers:
      - name: gamehub
        image: tejubagalad/gamehub:latest
        ports:
        - containerPort: 80	
        env:               # 🔹 CHANGE 2: inject Pod name
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
              
---
apiVersion: v1
kind: Service
metadata:
  name: gamehub-service
spec:
  selector:
    app: gamehub
  ports:
    - port: 80
      targetPort: 80
  type: NodePort          # 🔹 REQUIRED for Minikube access

